<img src='./numpy.png'/>

# Numpy full tutorial
**Creating Arrays from Python Lists**<br>
*First, we can use np.array to create arrays from Python lists:*


In [1]:
import numpy as np
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

*If we want to explicitly set the data type of the resulting array, we can use the dtype
keyword:*

In [4]:
np.array([1.,3.4,2.,],dtype='float32')

array([1. , 3.4, 2. ], dtype=float32)

Finally, unlike Python lists, NumPy arrays can explicitly be multidimensional; here’s
one way of initializing a multidimensional array using a list of lists:

In [5]:
# nested lists result in multidimensional arrays
np.array([range(i,i+3)for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [8]:
#another 
np.array([range(i,i+3)for i in [3,5,7]])

array([[3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

**Create a length-10 integer array filled with zeros**

In [9]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Create a 3x5 floating-point array filled with 1s**

In [10]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**create a 3*5 array filled with 3.14**

In [11]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

**Create a 3x3 identity matrix**


In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<h1 color='red'>Standard NumPy data types</h1>

bool_  Boolean (True or False) stored as a byte<br>
int_   Default integer type (same as C long ; normally either int64 or int32 )<br>
intc   Identical to C int (normally int32 or int64 )<br>
intp   Integer used for indexing (same as C ssize_t ; normally either int32 or int64 )<br>
int8   Byte (–128 to 127)<br>
int16  Integer (–32768 to 32767)<br>
int32  Integer (–2147483648 to 2147483647)<br>
int64  Integer (–9223372036854775808 to 9223372036854775807)<br>
uint8   Unsigned integer (0 to 255)<br>
uint16  Unsigned integer (0 to 65535)<br>
uint32  Unsigned integer (0 to 4294967295)<br>
uint64  Unsigned integer (0 to 18446744073709551615)<br>
float_  Shorthand for float64<br>
float16  Half-precision float: sign bit, 5 bits exponent, 10 bits mantissa<br>
float32  Single-precision float: sign bit, 8 bits exponent, 23 bits mantissa<br>
float64   Double-precision float: sign bit, 11 bits exponent, 52 bits mantissa<br>
complex_   Shorthand for complex128<br>
complex64   Complex number, represented by two 32-bit floats<br>
complex128  Complex number, represented by two 64-bit floats<br>

<h1>NumPy Array Attributes</h1>


In [13]:
import numpy as np
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [14]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [15]:
print("dtype:", x3.dtype)

dtype: int64


In [16]:
x1


array([5, 0, 3, 3, 7, 9])

In [17]:
x1[2]

3

<h1>Array Slicing: Accessing Subarrays</h1>

```
x[start:stop:step]
```

*One-dimensional subarrays*

In [21]:
x1


array([5, 0, 3, 3, 7, 9])

In [22]:
x1[:5] #first five elements

array([5, 0, 3, 3, 7])

In [23]:
x1[3:] #elements after index 3


array([3, 7, 9])

In [25]:
x1[2:4] #middle sub_array

array([3, 3])

In [26]:
x1[::2] #take 1st one and jump next 2

array([5, 3, 7])

In [28]:
x1[1::2] #take number 1 index and jump next 2

array([0, 3, 9])

In [29]:
x1[::-1] #reversed 

array([9, 7, 3, 3, 0, 5])

<h1>multidimensional sub_arrays

In [30]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [31]:
x2[:2,:3] #2 rows - 3 columns

array([[3, 5, 2],
       [7, 6, 8]])

In [32]:
x2[:3,::2] #every colums but same as in[26]

array([[3, 2],
       [7, 8],
       [1, 7]])

*Finally, subarray dimensions can even be reversed together:*


In [33]:
x2[::-1,::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

<h1>Accessing array rows and columns.
    

In [35]:
print(x2[:,0]) #first column  array([[3, 5, 2, 4],
                                 # [7, 6, 8, 8],
                                # [1, 6, 7, 7]])

[3 7 1]


In [36]:
print(x2[0,:])

[3 5 2 4]


*row and column value change*


In [37]:
x2 #previous

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [39]:
x2_new=x2 #copy from original
print(x2)


[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [41]:
x2[0,0]=10
print(x2)

[[10  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [48]:

print(x2[1,2]) #access row coloumn -[n1,n2]-n1-row,n2-coloumn

8
